spring:
  application:
    name: transfer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



application:
  kafka:
    bootstrap-servers: localhost:19092
    request-topic: transfer.inbound.request
    consumer-group-id: transfer-service-consumer-group
    response-topic: transfer.inbound.response